/*
 * IntroScreen.java
 *
 * Created on Jul 12, 2012, 11:27:01 AM
 */
package view;

import data.PartAndCause;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ButtonGroup;
import main.MainApp;

/**
 * With this view it's possible to select the items you wish to make a call for.
 * The standard format is: Machine:Specialiteit:Part:Cause: Free text
 * Something like this: "CRA:HH:Project:Cash:Vastloper: Machine loopt vast bij 
 * test transacties"
 * @author vm
 */
public class SelectionScreenCRA extends javax.swing.JPanel {

	PartAndCause pac = new PartAndCause();

	/** Creates new form Selection CRA */
	@SuppressWarnings("OverridableMethodCallInConstructor")
	public SelectionScreenCRA() {
		initComponents();

		//Group the radiobuttons to make sure only 1 is selected
		ButtonGroup radiobuttonGroup = new ButtonGroup();
		radiobuttonGroup.add(jRadioButtonCRA);
		radiobuttonGroup.add(jRadioButtonPCE);

		//Set the selection to the CRA radiobutton by default
		jRadioButtonCRA.setSelected(true);

		//Clear the comboBoxes
		jComboBoxPart.removeAllItems();
		jComboBoxCause.removeAllItems();

		pac.arrayListFill();

		fillComboBox();
		
		// Do this when something happens to the combobox
		jComboBoxPart.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				conditionalfillComboBox();
			}
		});

	}

	//Copy the Ticket String
	public void copy() {
	}

	public void fillComboBox() {
		// fill the ComboBox with the parts
		for (int i = 0; i < pac.part.size(); i++) {
			jComboBoxPart.addItem(pac.part.get(i));

		}
		for (int i = 0; i < pac.causeCash.size(); i++) {
			jComboBoxCause.addItem(pac.causeCash.get(i));
		}

	}

	public void conditionalfillComboBox() {
		//Make a conditional filled combobox to fill the right causes.
		String chosenPart = jComboBoxPart.getSelectedItem().toString();

		if (chosenPart.equals("CASH")) {
			jComboBoxCause.removeAllItems();

			for (int i = 0; i < pac.causeCash.size(); i++) {
				jComboBoxCause.addItem(pac.causeCash.get(i));
			}

		} else if (chosenPart.equals("COIN")) {
			jComboBoxCause.removeAllItems();

			for (int i = 0; i < pac.causeCoin.size(); i++) {
				jComboBoxCause.addItem(pac.causeCoin.get(i));
			}

		} else if (chosenPart.equals("CONNECTION")) {
			jComboBoxCause.removeAllItems();

			for (int i = 0; i < pac.causeConnection.size(); i++) {
				jComboBoxCause.addItem(pac.causeConnection.get(i));
			}

		} else if (chosenPart.equals("FINANCE")) {
			jComboBoxCause.removeAllItems();

			for (int i = 0; i < pac.causeFinance.size(); i++) {
				jComboBoxCause.addItem(pac.causeFinance.get(i));
			}

		} else if (chosenPart.equals("G4S")) {
			jComboBoxCause.removeAllItems();

			for (int i = 0; i < pac.causeG4S.size(); i++) {
				jComboBoxCause.addItem(pac.causeG4S.get(i));
			}
		} else if (chosenPart.equals("RPNT")) {
			jComboBoxCause.removeAllItems();

			for (int i = 0; i < pac.causeRpnt.size(); i++) {
				jComboBoxCause.addItem(pac.causeRpnt.get(i));
			}
		}

	}
	
	public void fillTicketString(){
		String ticketString = "";
		jTextFieldTicketString.setText(ticketString);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxCombiCall = new javax.swing.JCheckBox();
        jCheckBoxProject = new javax.swing.JCheckBox();
        jCheckBoxReturnCall = new javax.swing.JCheckBox();
        jButtonReturn = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();
        jLabelPart = new javax.swing.JLabel();
        jLabelCause = new javax.swing.JLabel();
        jLabelFreeText = new javax.swing.JLabel();
        jLabelTicketString = new javax.swing.JLabel();
        jTextFieldTicketString = new javax.swing.JTextField();
        jTextFieldFreeText = new javax.swing.JTextField();
        jLabelSpecial = new javax.swing.JLabel();
        jLabelMachine = new javax.swing.JLabel();
        jRadioButtonCRA = new javax.swing.JRadioButton();
        jRadioButtonPCE = new javax.swing.JRadioButton();
        jComboBoxCause = new javax.swing.JComboBox();
        jComboBoxPart = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(254, 254, 254));

        jCheckBoxCombiCall.setText("Combi Call");
        jCheckBoxCombiCall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxCombiCallActionPerformed(evt);
            }
        });

        jCheckBoxProject.setText("Project");
        jCheckBoxProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxProjectActionPerformed(evt);
            }
        });

        jCheckBoxReturnCall.setText("Herhaal Call");

        jButtonReturn.setText("Terug");
        jButtonReturn.setMaximumSize(new java.awt.Dimension(100, 30));
        jButtonReturn.setPreferredSize(new java.awt.Dimension(100, 30));
        jButtonReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReturnActionPerformed(evt);
            }
        });

        jButtonReset.setText("Reset");
        jButtonReset.setMaximumSize(new java.awt.Dimension(100, 30));
        jButtonReset.setPreferredSize(new java.awt.Dimension(100, 30));
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        jLabelPart.setText("Onderdeel");

        jLabelCause.setText("Oorzaak");

        jLabelFreeText.setText("Vrije tekst");

        jLabelTicketString.setText("Ticket String");

        jTextFieldTicketString.setEditable(false);

        jLabelSpecial.setText("Specialiteit");

        jLabelMachine.setText("Machine");

        jRadioButtonCRA.setText("CRA");

        jRadioButtonPCE.setText("PC/E");

        jComboBoxCause.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxPart.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonReturn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 639, Short.MAX_VALUE)
                                .addComponent(jButtonReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelFreeText)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 770, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelTicketString)
                                    .addComponent(jLabelSpecial)
                                    .addComponent(jLabelPart)
                                    .addComponent(jLabelCause))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldFreeText, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
                                    .addComponent(jTextFieldTicketString, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButtonCRA)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jRadioButtonPCE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jComboBoxCause, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jCheckBoxCombiCall)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jCheckBoxProject)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jCheckBoxReturnCall))
                                        .addComponent(jComboBoxPart, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(40, 40, 40))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelMachine)
                        .addContainerGap(820, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonReturn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMachine)
                    .addComponent(jRadioButtonCRA)
                    .addComponent(jRadioButtonPCE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxCombiCall)
                    .addComponent(jCheckBoxProject)
                    .addComponent(jCheckBoxReturnCall)
                    .addComponent(jLabelSpecial))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPart)
                    .addComponent(jComboBoxPart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCause)
                    .addComponent(jComboBoxCause, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFreeText)
                    .addComponent(jTextFieldFreeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTicketString)
                    .addComponent(jTextFieldTicketString, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(144, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

	private void jCheckBoxCombiCallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxCombiCallActionPerformed
		//
	}//GEN-LAST:event_jCheckBoxCombiCallActionPerformed

	private void jCheckBoxProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxProjectActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_jCheckBoxProjectActionPerformed

	private void jButtonReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReturnActionPerformed
		// This button serves as a return to the main screen
		MainApp.getInstance().switchPanel(new view.IntroScreen());
	}//GEN-LAST:event_jButtonReturnActionPerformed

	private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
		fillComboBox();

	}//GEN-LAST:event_jButtonResetActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonReset;
    private javax.swing.JButton jButtonReturn;
    private javax.swing.JCheckBox jCheckBoxCombiCall;
    private javax.swing.JCheckBox jCheckBoxProject;
    private javax.swing.JCheckBox jCheckBoxReturnCall;
    private javax.swing.JComboBox jComboBoxCause;
    private javax.swing.JComboBox jComboBoxPart;
    private javax.swing.JLabel jLabelCause;
    private javax.swing.JLabel jLabelFreeText;
    private javax.swing.JLabel jLabelMachine;
    private javax.swing.JLabel jLabelPart;
    private javax.swing.JLabel jLabelSpecial;
    private javax.swing.JLabel jLabelTicketString;
    private javax.swing.JRadioButton jRadioButtonCRA;
    private javax.swing.JRadioButton jRadioButtonPCE;
    private javax.swing.JTextField jTextFieldFreeText;
    private javax.swing.JTextField jTextFieldTicketString;
    // End of variables declaration//GEN-END:variables
}
